spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/torneosdb
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update