spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://torneosdb_4fkm_user:TEh3pfyZNwWfSmf4QU96VWtdAkvPhfNE@dpg-da5gi78jo6nc73cgg6sg-a.oregon-postgres.render.com/torneosdb_4fkm
spring.datasource.username=postgres
spring.datasource.password=TEh3pfyZNwWfSmf4QU96VWtdAkvPhfNE
spring.jpa.hibernate.ddl-auto=create