spring.datasource.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://torneosdb_4fkm_user:TEh3pfyZNwWfSmf4QU96VWtdAkvPhfNE@dpg-da5gi78jo6nc73cgg6sg-a/torneosdb_4fkm

spring.datasource.username=torneosdb_4fkm_user
spring.datasource.password=TEh3pfyZNwWfSmf4QU96VWtdAkvPhfNE

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
